### ISSUE TITLE
the result is empty

### ISSUE THREAD

**Issue by jnreyy** [ZLaxtert/cc-checkerV4#1]
![438102005_453581087260941_6631047829660547439_n](https://github.com/ZLaxtert/cc-checkerV4/assets/127049000/aa1a0893-f358-4f68-8b86-3eedb6727376)

**Comment by Cesar2332xwx** [comment]
I think the API is down but we have to wait for Darkcode to say something.

**Comment by ochocetre** [comment]
explain

**Comment by AxureXd** [comment]
> if you want to run the tool you need apikey

where we can get it @ZLaxtert

**Comment by AxureXd** [comment]
@ZLaxtert

**Comment by ZLaxtert** [comment]
you can buy it in my site https://darkxcode.site

**Comment by AxureXd** [comment]
> you can buy it in my site https://darkxcode.site

naw

**Comment by AxureXd** [comment]
too much costly
